# Configuración de la Base de Datos H2 en memoria
spring.datasource.url=jdbc:h2:mem:ticketdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Habilitar la consola de H2 en el navegador para verificar tus datos
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Actualización automática del esquema de la base de datos
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true